# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/One Drive/OneDrive - whu.edu.cn/Learning/computerOrg/lab_related/Computer-Organization/coursecodes/day3/Single_CPU/icf.xdc

# IP: ip/RAM_B/RAM_B.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet
